import { ArrowLeft, Bookmark, Clock3, ExternalLink, Share2, Sparkles } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { AppShell } from "@/components/AppShell";
import { trpc } from "@/lib/trpc";

export default function ArticlePage() {
  const [, setLocation] = useLocation();
  const [, params] = useRoute("/news/article/:slug");
  const query = trpc.market.news.useQuery(undefined, { staleTime: 60_000 });
  const article = query.data?.find((item) => item.id === params?.slug) ?? query.data?.[0];
  if (!article) return <AppShell><div className="page-shell loading-state"><p>Loading story…</p></div></AppShell>;
  return <AppShell><div className="page-shell article-shell"><button type="button" className="back-button" onClick={() => setLocation("/news")}><ArrowLeft size={14} /> Back to research</button><div className="article-layout"><article><div className="article-header"><span className="news-meta"><b>{article.category}</b><span>·</span>{article.source}</span><h1>{article.headline}</h1><p className="article-dek">A concise market brief on the drivers, positioning, and signals behind today&apos;s price action.</p><div className="article-meta"><span>By Northstar Research</span><span>·</span><span><Clock3 size={13} /> {article.time}</span><span>·</span><span>{article.readTime}</span><div className="article-actions"><button type="button" className="icon-button bordered"><Bookmark size={15} /></button><button type="button" className="icon-button bordered"><Share2 size={15} /></button></div></div></div><div className={`article-hero news-${article.tone}`}><Sparkles size={34} /><span>Northstar Research</span></div><div className="article-body"><p>Markets rarely move for one reason. Today&apos;s tape reflects a softer inflation impulse, a modest reset in policy expectations, and renewed appetite for the companies with the strongest earnings revisions.</p><h2>What changed</h2><p>The important move is not simply the index print. Leadership is broadening, real yields are easing at the margin, and liquidity is beginning to travel across more of the market. That combination can support a durable trend — but it also creates a higher bar for the next round of data.</p><blockquote>“The best signal is often the one that survives a change in narrative.”</blockquote><h2>What to watch next</h2><p>Keep an eye on breadth, forward guidance, and the shape of the curve. The data below is presented as research context, not a forecast or personalized recommendation.</p><div className="article-callout"><ExternalLink size={15} /><span><strong>Research context.</strong> Northstar is an information platform. Investment decisions involve risk, and past performance is not indicative of future results.</span></div></div></article><aside className="article-rail"><div className="section-card rail-card"><span className="section-eyebrow">Related signal</span><h3>Track the assets in this story</h3><Link href="/stocks/nvda" className="related-asset"><span className="asset-mark asset-stock">NV</span><span><b>NVDA</b><small>NVIDIA Corporation</small></span><strong className="positive">+2.96%</strong></Link><Link href="/stocks/aapl" className="related-asset"><span className="asset-mark asset-stock">AP</span><span><b>AAPL</b><small>Apple Inc.</small></span><strong className="positive">+0.49%</strong></Link><Link href="/markets" className="text-button">Explore markets <ExternalLink size={13} /></Link></div></aside></div></div></AppShell>;
}
